### PR TITLE
DE-1668 Added Chunking to downloads in Sa.py

### PR DESCRIPTION
**Pull request by niallscc**

### CODE REVIEW

**Comment by niallscc** [comment]
Not sure what to do for the jupyter notebook on this one for documentation. I created this pr as a placeholder because the code is done but I would like feedback on what to do on that front.

**Comment by niallscc** [comment]
@gnilrets Good call on removing the length if statement and fixing ignore_index. I thought that we were leaving all commits? I was going to squash it but as part of the pip my understanding was that I needed to leave all commits as part of the record. Please advise.

**Comment by gnilrets** [comment]
@niallscc - Every round of review should be a single commit.  In this case, you push a commit, and then circle came back with a failure.  You then fixed the oops and requested a review (maybe in the other order, but I wouldn't have gotten to it that quick).  So now I've got two commits to review, one of which I really don't need to see and should just be squashed onto the commit you want me to review.

Now, after you've made changes requested in a review, submit that as a new commit.  If there end up being more "oops" commits, then squash those onto the new commit, but don't modify the one that has already undergone review.  That way I can easily focus on just the changes made since the last round of review.

**Comment by gnilrets** [comment]
Otherwise, this all looks good.  I'm going to merge this into the v0.2.6 branch.  Not sure what it's going to do to this review history.

**Pull request merged**
